[CREATED] created building list view + filtering
wecode-bootcamp-korea/27-2nd-workfolio-backend pull request #13
Opened 2021-12-15 05:37 UTC by eslerkang

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 빌딩 리스트 GET 메소드 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
- 도시, 구, 이름, 가격 범위, 체크인, 체크아웃 가능 여부 등으로 필터링 하여 pagination되도록 빌딩 리스트 반환
- 높은/낮은 가격순, 인기순, 높은/낮은 인원수 등으로 order_by 적용

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 체크인/체크아웃을 통해 건물과 사무실 사이에서 예약 가능한 '빌딩'만을 표출할 수 있는 로직에 대해 고민했습니다.
- 다양한 필터들과 정렬로 값이 있을때/없을때 핸들링하는 방식에 대해 생각해봤습니다.
- 잘못된 필터값이 입력될 경우 어떤 방식으로 에러핸들링 할 지 고민해봤습니다.

<br />

## :: 기타 질문 및 특이 사항

2021-12-16 01:20 UTC, bigfanoftim requested changes

2021-12-16 01:20 UTC, bigfanoftim commented on offices/views.py
> +            ORDER = {
```suggestion
            ordering = {
```

2021-12-16 01:20 UTC, bigfanoftim commented on offices/views.py
> +            QUERY = {
```suggestion
            filter_field = {
```

2021-12-16 01:20 UTC, bigfanoftim commented on offices/views.py
> +            offices = [office[0] for office in offices]
```suggestion
            office_ids = [office[0] for office in offices]
```

2021-12-16 01:56 UTC, eslerkang commented on offices/views.py
> +            ORDER = {
ordering을 orders로, filter_field를 filters로 변경했습니다

2021-12-17 01:18 UTC, bigfanoftim approved these changes
LGTM 😎

2021-12-17 01:19 UTC, merged